# application.yml is the configuration file for the product-service application.
# It defines various settings such as the application name, server port, Eureka client configuration,
# and SpringDoc/Swagger UI paths for API documentation.
server:
  port: 8081
spring:
  application:
    name: product-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html